spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: customer
    password: customer

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  metrics:
    tags:
      application: customer-service
      server.port: "8081"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [trace=%X{traceId},span=%X{spanId}] [%t] %c{1} - %m%n"
